spring.application.name=app

app.frontend-bg-color=${FRONTEND_BG_COLOR:green}
app.backend-version=${BACKEND_VERSION:0.1.0}
app.pgdb-enable=${PGDB_ENABLE:false}
app.pgdb-url=${PGDB_URL:jdbc:postgresql://postgres:5432/demo_db}
app.oom-enable=${OOM_ENABLE:false}
app.oom-time=${OOM_TIME:0}

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
