services:
  backend:
    image: ${BACKEND_IMAGE:-simonangelfong/gitops-demo-backend}
    environment:
      BACKEND_VERSION: ${BACKEND_VERSION:-1.4.2}
      # FRONTEND_BG_COLOR: ${FRONTEND_BG_COLOR:-green}
      FRONTEND_BG_COLOR: ${FRONTEND_BG_COLOR:-red}
      PGDB_ENABLE: ${PGDB_ENABLE:-false}
      PGDB_URL: ${PGDB_URL:-jdbc:postgresql://postgres:5432/demo_db}
      OOM_ENABLE: ${OOM_ENABLE:-false}
      OOM_TIME: ${OOM_TIME:-0}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/api/healthz"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  frontend:
    image: ${FRONTEND_IMAGE:-simonangelfong/gitops-demo-frontend}
    environment:
      BACKEND_URL: http://backend:8080
      NGINX_ENVSUBST_FILTER: BACKEND_URL
    ports:
      - "8000:8080"
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    depends_on:
      backend:
        condition: service_healthy
